version: "3.0"

services:
  db:
    image: postgres:14.0
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123

  adminer:
    image: adminer
    ports:
      - 8080:8080

  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
